name: budget-manager-prod
services:
  nginx:
    depends_on:
      - client
      - backend
    restart: always # because it is routing traffic to our entire app
    container_name: nginx
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '80:80'
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./client:/app
    env_file:
      - ./env/client.env
    restart: on-failure
    container_name: client
  backend:
    depends_on:
      - mongodb
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    restart: on-failure
    container_name: backend
    volumes:
      - ./backend:/app
    env_file:
      - ./env/common.env
      - ./env/backend.env
  mongodb:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: mongodb
    ports:
      - '27017-27019:27017-27019'
    volumes:
      - ./db/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
      - ./db/data:/data/db
    env_file:
      - ./env/common.env
