http://localhost:3001/categories HTTP/1.1

###

POST http://localhost:3001/categories HTTP/1.1
content-type: application/json

{
  "name": "Groceries",
  "maxLimit": 3000
}

###

PATCH http://localhost:3001/categories/63014cdc02b9c4e59c415f0c HTTP/1.1
content-type: application/json

{
  "maxLimit": 4000
}

###

DELETE http://localhost:3001/categories/63015082fedec024991eb37a HTTP/1.1

