http://localhost:3001/tags HTTP/1.1

###

POST http://localhost:3001/tags HTTP/1.1
content-type: application/json

{
  "name": "Test"
}

###

PATCH http://localhost:3001/tags/630154258aa77cb8736e0a21 HTTP/1.1
content-type: application/json

{
  "name": "daily_expense"
}

###

DELETE http://localhost:3001/tags/630154768aa77cb8736e0a26 HTTP/1.1

