http://localhost:3001/wallets HTTP/1.1

###

POST http://localhost:3001/wallets HTTP/1.1
content-type: application/json

{
  "name": "Savings bank",
  "balance": 10000
}

###

PATCH http://localhost:3001/wallets/630156449b61a1117c915aca HTTP/1.1
content-type: application/json

{
  "name": "Credit card"
}

###

DELETE http://localhost:3001/wallets/630156aa9b61a1117c915ad2 HTTP/1.1

